### ISSUE TITLE
Time to bring C# to netbeans?

### ISSUE THREAD

**Issue by Chris2011** [ChristianWulf/CSharpGrammar#3]
Hey man,

I'm working on a plugin to implement C# into netbeans: https://github.com/Chris2011/CSharp-for-netbeans

Do you want to help me with this or do you have time? First I read a lot of tutorials to implement a new language into netbeans. I read about ANTLR that I need a grammar file and with this file, the ANTLR api (In netbeans) creates a lot of other files, that I need. Lexer, token files? Don't know. Maybe I don't need it because you already created it. I don't know atm.

First thing that I tried is ANTLRWorks2: http://tunnelvisionlabs.com/products/demo/antlrworks. It's an application created as a netbeans standalone application, to have syntax highlighting for .g files and generator. When I tried to open your file and hit the action "Generate Recognizer..." I got the error: This command is not valid in legacy (ANTLR 3) mode. But I don't know which. Possible that the syntax, which you need, is available in ANTLR 4 first and not in 3? Whatever I created a bug: https://github.com/tunnelvisionlabs/antlrworks2/issues/55

So let me know, if the project sounds great for you to help or not.

Cheers

Chris

**Comment by ChristianWulf** [comment]
Hi Chris,

unfortunately, I have no time and...Netbeans is not my IDE, to be honest.

But I can tell you the following:

 1. My ANTLR-based C# grammar is written in ANTLR-3 syntax. Probably
    this is the cause of why ANTLRWorks does not work ;)
 2. In general, ANTLR generates the lexer and the parser of this grammar
    file. With these two Java classes, you can build an abstract syntax
    tree for each C# input file.

Cheers,
Christian


Am 21.08.2015 um 13:41 schrieb Chris2011:

**Comment by Chris2011** [comment]
Thx for your description, now it's a bit clearer for me :).

**Comment by Chris2011** [comment]
So when I understand it right: those files are the generated files out of your grammar file: https://github.com/ChristianWulf/CSharpGrammar/tree/master/antlr-generated/lang/csharp

right? So when I don't want to generate it by myself, I can use this files, right?

**Comment by ChristianWulf** [comment]
Right. Some of the classes are generated helper classes. See the
following example in order to get an impression of how these classes
should be used:

https://github.com/ChristianWulf/CSharpGrammar/blob/master/src/example/Main.java

Am 02.09.2015 um 15:48 schrieb Chris2011:
>
> So when I understand it right: those files are the generated files out
> of your grammar file:
> https://github.com/ChristianWulf/CSharpGrammar/tree/master/antlr-generated/lang/csharp
>
> right? So when I don't want to generate it by myself, I can use this
> files, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChristianWulf/CSharpGrammar/issues/3#issuecomment-137087748>.
>

-- 
M.Sc. Christian Wulf
Research Assistant

Software Engineering Group
Dept. Computer Science
Christian-Albrechts-Platz 4
University of Kiel
24118 Kiel, Germany

Room:  1213
Phone: +49 431 880 2776
Fax:   +49 431 880 7617
Email: chw@informatik.uni-kiel.de
WWW:   http://se.informatik.uni-kiel.de/

**Comment by Chris2011** [comment]
Thx I will have a look :)

**Comment by Chris2011** [comment]
I would like to test this tutorial to implement it into netbeans: http://wiki.netbeans.org/New_Language_Support_Tutorial_Antlr. At point 2 they said I need a language hierarchy file. Which one is it at your repo, that I can use? Or maybe a token file or so.

**Comment by Chris2011** [comment]
Ok it means that I need the token file which was generated from antlr

**Comment by detectivejd** [comment]
Hello, I was interested in knowing what the development of the plugin for C # is going? Greetings.

**Comment by Chris2011** [comment]
Hi,

if you mean for netbeans, please see this repo: https://github.com/Chris2011/CSharp-for-netbeans

This ticket here is not the right place :)


Cheers

Chris
